spring:
  config:
    import:
      - optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: ${JWT_ACCESS_EXPIRATION}


  server:
    address: 0.0.0.0  # 모든 IP에서 접근 가능하게 설정

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

google:
  places:
    key: ${GOOGLE-API-KEY}

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}
