name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # 사용 중인 자바 버전으로 변경
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Create PEM file
        run: |
          echo "${{ secrets.EC2_KEY }}" > with_run_key.pem
          chmod 400 with_run_key.pem

      - name: Copy JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i with_run_key.pem build/libs/*.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/app.jar

      - name: Run JAR on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i with_run_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # 기존 프로세스 종료
            pkill -f 'java -jar' || true

            # 새로 실행
            nohup java -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &
          EOF
